strategy = {("Wall", "Wall", "Empty", "Empty", "Empty"): "GoDown", ("Wall", "Wall", "Empty", "Empty", "Point"): "GoUp",
            ("Wall", "Wall", "Empty", "Point", "Empty"): "GoUp",
            ("Wall", "Wall", "Empty", "Point", "Point"): "TakePoint",
            ("Wall", "Wall", "Point", "Empty", "Empty"): "GoDown",
            ("Wall", "Wall", "Point", "Empty", "Point"): "GoDown",
            ("Wall", "Wall", "Point", "Point", "Empty"): "GoUp", ("Wall", "Wall", "Point", "Point", "Point"): "GoLeft",
            ("Wall", "Empty", "Empty", "Wall", "Empty"): "GoUp", ("Wall", "Empty", "Empty", "Wall", "Point"): "GoRight",
            ("Wall", "Empty", "Empty", "Empty", "Empty"): "GoRight",
            ("Wall", "Empty", "Empty", "Empty", "Point"): "GoDown",
            ("Wall", "Empty", "Empty", "Point", "Empty"): "GoUp",
            ("Wall", "Empty", "Empty", "Point", "Point"): "GoDown",
            ("Wall", "Empty", "Point", "Wall", "Empty"): "GoLeft",
            ("Wall", "Empty", "Point", "Wall", "Point"): "GoRight",
            ("Wall", "Empty", "Point", "Empty", "Empty"): "GoLeft",
            ("Wall", "Empty", "Point", "Empty", "Point"): "GoUp",
            ("Wall", "Empty", "Point", "Point", "Empty"): "GoUp", ("Wall", "Empty", "Point", "Point", "Point"): "GoUp",
            ("Wall", "Point", "Empty", "Wall", "Empty"): "GoUp", ("Wall", "Point", "Empty", "Wall", "Point"): "GoUp",
            ("Wall", "Point", "Empty", "Empty", "Empty"): "GoRight",
            ("Wall", "Point", "Empty", "Empty", "Point"): "TakePoint",
            ("Wall", "Point", "Empty", "Point", "Empty"): "GoDown",
            ("Wall", "Point", "Empty", "Point", "Point"): "GoUp",
            ("Wall", "Point", "Point", "Wall", "Empty"): "GoUp",
            ("Wall", "Point", "Point", "Wall", "Point"): "TakePoint",
            ("Wall", "Point", "Point", "Empty", "Empty"): "GoUp",
            ("Wall", "Point", "Point", "Empty", "Point"): "TakePoint",
            ("Wall", "Point", "Point", "Point", "Empty"): "GoRight",
            ("Wall", "Point", "Point", "Point", "Point"): "GoUp",
            ("Empty", "Wall", "Wall", "Empty", "Empty"): "GoLeft",
            ("Empty", "Wall", "Wall", "Empty", "Point"): "TakePoint",
            ("Empty", "Wall", "Wall", "Point", "Empty"): "TakePoint",
            ("Empty", "Wall", "Wall", "Point", "Point"): "GoLeft",
            ("Empty", "Wall", "Empty", "Empty", "Empty"): "GoUp",
            ("Empty", "Wall", "Empty", "Empty", "Point"): "GoLeft",
            ("Empty", "Wall", "Empty", "Point", "Empty"): "TakePoint",
            ("Empty", "Wall", "Empty", "Point", "Point"): "TakePoint",
            ("Empty", "Wall", "Point", "Empty", "Empty"): "GoRight",
            ("Empty", "Wall", "Point", "Empty", "Point"): "GoDown",
            ("Empty", "Wall", "Point", "Point", "Empty"): "GoRight",
            ("Empty", "Wall", "Point", "Point", "Point"): "GoUp",
            ("Empty", "Empty", "Wall", "Wall", "Empty"): "GoUp",
            ("Empty", "Empty", "Wall", "Wall", "Point"): "TakePoint",
            ("Empty", "Empty", "Wall", "Empty", "Empty"): "GoUp",
            ("Empty", "Empty", "Wall", "Empty", "Point"): "GoDown",
            ("Empty", "Empty", "Wall", "Point", "Empty"): "GoRight",
            ("Empty", "Empty", "Wall", "Point", "Point"): "GoDown",
            ("Empty", "Empty", "Empty", "Wall", "Empty"): "GoLeft",
            ("Empty", "Empty", "Empty", "Wall", "Point"): "GoDown",
            ("Empty", "Empty", "Empty", "Empty", "Empty"): "GoUp",
            ("Empty", "Empty", "Empty", "Empty", "Point"): "GoUp",
            ("Empty", "Empty", "Empty", "Point", "Empty"): "GoRight",
            ("Empty", "Empty", "Empty", "Point", "Point"): "GoDown",
            ("Empty", "Empty", "Point", "Wall", "Empty"): "GoRight",
            ("Empty", "Empty", "Point", "Wall", "Point"): "GoUp",
            ("Empty", "Empty", "Point", "Empty", "Empty"): "TakePoint",
            ("Empty", "Empty", "Point", "Empty", "Point"): "GoUp",
            ("Empty", "Empty", "Point", "Point", "Empty"): "GoUp",
            ("Empty", "Empty", "Point", "Point", "Point"): "GoRight",
            ("Empty", "Point", "Wall", "Wall", "Empty"): "GoUp",
            ("Empty", "Point", "Wall", "Wall", "Point"): "TakePoint",
            ("Empty", "Point", "Wall", "Empty", "Empty"): "GoDown",
            ("Empty", "Point", "Wall", "Empty", "Point"): "GoLeft",
            ("Empty", "Point", "Wall", "Point", "Empty"): "GoRight",
            ("Empty", "Point", "Wall", "Point", "Point"): "TakePoint",
            ("Empty", "Point", "Empty", "Wall", "Empty"): "GoUp",
            ("Empty", "Point", "Empty", "Wall", "Point"): "GoRight",
            ("Empty", "Point", "Empty", "Empty", "Empty"): "TakePoint",
            ("Empty", "Point", "Empty", "Empty", "Point"): "GoRight",
            ("Empty", "Point", "Empty", "Point", "Empty"): "GoDown",
            ("Empty", "Point", "Empty", "Point", "Point"): "GoDown",
            ("Empty", "Point", "Point", "Wall", "Empty"): "TakePoint",
            ("Empty", "Point", "Point", "Wall", "Point"): "GoLeft",
            ("Empty", "Point", "Point", "Empty", "Empty"): "TakePoint",
            ("Empty", "Point", "Point", "Empty", "Point"): "TakePoint",
            ("Empty", "Point", "Point", "Point", "Empty"): "GoUp",
            ("Empty", "Point", "Point", "Point", "Point"): "TakePoint",
            ("Point", "Wall", "Wall", "Empty", "Empty"): "GoDown",
            ("Point", "Wall", "Wall", "Empty", "Point"): "GoRight",
            ("Point", "Wall", "Wall", "Point", "Empty"): "GoUp", ("Point", "Wall", "Wall", "Point", "Point"): "GoUp",
            ("Point", "Wall", "Empty", "Empty", "Empty"): "GoRight",
            ("Point", "Wall", "Empty", "Empty", "Point"): "TakePoint",
            ("Point", "Wall", "Empty", "Point", "Empty"): "GoDown",
            ("Point", "Wall", "Empty", "Point", "Point"): "GoDown",
            ("Point", "Wall", "Point", "Empty", "Empty"): "GoLeft",
            ("Point", "Wall", "Point", "Empty", "Point"): "GoLeft",
            ("Point", "Wall", "Point", "Point", "Empty"): "TakePoint",
            ("Point", "Wall", "Point", "Point", "Point"): "GoDown",
            ("Point", "Empty", "Wall", "Wall", "Empty"): "GoRight",
            ("Point", "Empty", "Wall", "Wall", "Point"): "GoDown",
            ("Point", "Empty", "Wall", "Empty", "Empty"): "GoUp",
            ("Point", "Empty", "Wall", "Empty", "Point"): "GoDown",
            ("Point", "Empty", "Wall", "Point", "Empty"): "GoUp",
            ("Point", "Empty", "Wall", "Point", "Point"): "GoLeft",
            ("Point", "Empty", "Empty", "Wall", "Empty"): "GoRight",
            ("Point", "Empty", "Empty", "Wall", "Point"): "GoRight",
            ("Point", "Empty", "Empty", "Empty", "Empty"): "GoRight",
            ("Point", "Empty", "Empty", "Empty", "Point"): "GoRight",
            ("Point", "Empty", "Empty", "Point", "Empty"): "GoUp",
            ("Point", "Empty", "Empty", "Point", "Point"): "GoLeft",
            ("Point", "Empty", "Point", "Wall", "Empty"): "TakePoint",
            ("Point", "Empty", "Point", "Wall", "Point"): "GoUp",
            ("Point", "Empty", "Point", "Empty", "Empty"): "TakePoint",
            ("Point", "Empty", "Point", "Empty", "Point"): "GoRight",
            ("Point", "Empty", "Point", "Point", "Empty"): "GoLeft",
            ("Point", "Empty", "Point", "Point", "Point"): "GoLeft",
            ("Point", "Point", "Wall", "Wall", "Empty"): "GoUp", ("Point", "Point", "Wall", "Wall", "Point"): "GoUp",
            ("Point", "Point", "Wall", "Empty", "Empty"): "TakePoint",
            ("Point", "Point", "Wall", "Empty", "Point"): "GoDown",
            ("Point", "Point", "Wall", "Point", "Empty"): "TakePoint",
            ("Point", "Point", "Wall", "Point", "Point"): "TakePoint",
            ("Point", "Point", "Empty", "Wall", "Empty"): "TakePoint",
            ("Point", "Point", "Empty", "Wall", "Point"): "GoRight",
            ("Point", "Point", "Empty", "Empty", "Empty"): "GoUp",
            ("Point", "Point", "Empty", "Empty", "Point"): "TakePoint",
            ("Point", "Point", "Empty", "Point", "Empty"): "GoRight",
            ("Point", "Point", "Empty", "Point", "Point"): "GoRight",
            ("Point", "Point", "Point", "Wall", "Empty"): "GoRight",
            ("Point", "Point", "Point", "Wall", "Point"): "GoDown",
            ("Point", "Point", "Point", "Empty", "Empty"): "GoDown",
            ("Point", "Point", "Point", "Empty", "Point"): "TakePoint",
            ("Point", "Point", "Point", "Point", "Empty"): "GoUp",
            ("Point", "Point", "Point", "Point", "Point"): "TakePoint"}
action = {
    "GoUp": 1,
    "GoDown": 2,
    "GoRight": 3,
    "GoLeft": 4,
    "TakePoint": 5
}

state = {
    "Wall": -1,
    "Empty": 0,
    "Point": 1
}

translated_strategy = {tuple(state[i] for i in k): action[v] for k, v in strategy.items()}
print(translated_strategy)

with open("last_strategy.txt","w") as f:
    f.write(str(translated_strategy))